# Generated by Django 3.0.6 on 2020-06-20 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(db_index=True, max_length=20)),
                ('slug', models.SlugField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'label',
                'verbose_name_plural': 'labels',
                'ordering': ('label_name',),
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.FloatField(blank=True, db_index=True, null=True)),
                ('height', models.FloatField(blank=True, db_index=True, null=True)),
                ('depth', models.FloatField(blank=True, db_index=True, null=True)),
                ('weight', models.FloatField(blank=True, db_index=True, null=True)),
                ('quality_checking', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], db_index=True, max_length=3)),
                ('freshness_duration', models.FloatField(blank=True, db_index=True, null=True)),
                ('when_packeting', models.CharField(db_index=True, max_length=50)),
                ('each_box_contains', models.FloatField(blank=True, db_index=True, null=True)),
            ],
            options={
                'verbose_name': 'specification',
                'verbose_name_plural': 'specifications',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('feature', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('available', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.Category')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Label')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Specification')),
            ],
            options={
                'ordering': ('created',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
