# Generated by Django 3.0.6 on 2020-06-20 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specification',
            options={'ordering': ('width',), 'verbose_name': 'specification', 'verbose_name_plural': 'specifications'},
        ),
    ]
