# Generated by Django 3.0.6 on 2020-06-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200620_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specification',
            options={},
        ),
        migrations.AlterField(
            model_name='specification',
            name='depth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='specification',
            name='each_box_contains',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='specification',
            name='freshness_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='specification',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='specification',
            name='quality_checking',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specification',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='specification',
            name='when_packeting',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='specification',
            name='width',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
