# Generated by Django 3.0.6 on 2020-06-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200620_1815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specification',
            options={'ordering': ('width',), 'verbose_name': 'specification', 'verbose_name_plural': 'specifications'},
        ),
        migrations.AlterField(
            model_name='item',
            name='available',
            field=models.CharField(choices=[('In Stock', 'In Stock'), ('Out of Stock', 'Out of Stock')], max_length=12),
        ),
    ]
