# Generated by Django 3.0.6 on 2020-06-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200620_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='specification',
            name='spec_name',
            field=models.CharField(default='Name', max_length=50),
            preserve_default=False,
        ),
    ]
