# Generated by Django 3.0.6 on 2020-06-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200620_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='spec_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
