# Generated by Django 3.0.6 on 2020-06-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200620_2034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
        migrations.AlterField(
            model_name='item',
            name='available',
            field=models.CharField(choices=[('In Stock', 'In Stock'), ('Out Of Stock', 'Out of Stock')], max_length=12),
        ),
        migrations.AlterIndexTogether(
            name='item',
            index_together=set(),
        ),
    ]
