# Generated by Django 3.0.6 on 2020-06-29 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_order_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='street_address',
            new_name='shipping_address',
        ),
    ]
